Moved install scripts to install/ directory

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -5,80 +5,37 @@ DOTFILES=$HOME/.dotfiles
 # Install required dependencies
 # --------------------------------------------------------------------------------------------------
 
-echo "Installing ZSH and Git"
 sudo apt install zsh git php nodejs ack-grep
-
-# --------------------------------------------------------------------------------------------------
-# Enable OhMyZSH
-# --------------------------------------------------------------------------------------------------
-
-echo "Installing OhMyZSH"
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
-
-# --------------------------------------------------------------------------------------------------
-# Enable ZSH
-# --------------------------------------------------------------------------------------------------
-
-echo "Changing to use ZSH"
-sudo chsh -s /bin/zsh
 
 # --------------------------------------------------------------------------------------------------
 # Clone dotfiles repository
 # --------------------------------------------------------------------------------------------------
 
-echo "Cloning to $DOTFILES"
 git clone git@github.com:pxgamer/dotfiles.git $DOTFILES
-
-# --------------------------------------------------------------------------------------------------
-# Remove old files
-# --------------------------------------------------------------------------------------------------
-
-echo "Removing old files"
-rm -rf \
-  $HOME/.gitconfig \
-  $HOME/.gitignore \
-  $HOME/.zshrc \
-  $HOME/.zprofile \
-  $HOME/.gnupg/gpg.conf
-
-# --------------------------------------------------------------------------------------------------
-# Symlinks
-# --------------------------------------------------------------------------------------------------
-
-echo "Adding symlinks for new files"
-
-# Git Files
-ln -s $DOTFILES/git/gitconfig $HOME/.gitconfig
-ln -s $DOTFILES/git/gitignore $HOME/.gitignore
-
-# ZSH Files
-ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc
-ln -s $DOTFILES/zsh/zprofile $HOME/.zprofile
-
-# GPG Files
-ln -s $DOTFILES/gnupg/gpg.conf $HOME/.gnupg/gpg.conf
 
 # --------------------------------------------------------------------------------------------------
 # Install additional binaries
 # --------------------------------------------------------------------------------------------------
 
-echo "Configuring binaries"
-
-# Composer
-sh $DOTFILES/development/composer.sh
+source  $DOTFILES/install/link.sh
+source  $DOTFILES/install/composer.sh
 
 # --------------------------------------------------------------------------------------------------
 # Cleanup
 # --------------------------------------------------------------------------------------------------
 
-echo "Removing ZSH dumps"
 rm -f $HOME/.zcompdump*
 
-echo "Removing unrequired packages"
 sudo apt autoremove
 
 # --------------------------------------------------------------------------------------------------
-# Switch to ZSH
+# Enable ZSH
 # --------------------------------------------------------------------------------------------------
 
-exec zsh
+if ! command_exists zsh; then
+    echo "zsh not found. Please install and then re-run installation scripts"
+    exit 1
+elif ! [[ $SHELL =~ .*zsh.* ]]; then
+    echo "Configuring zsh as default shell"
+    chsh -s $(which zsh)
+fi
